server:
  port: 8084

spring:
  application:
    name: ms-auth-service
  datasource:
    url: jdbc:h2:mem:ms_auth
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

jwt:
  secret: clave_secreta_en_base_64_con_32_bits_porque_es_el_minimo